name: flim-buchel-2025
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-image=0.25
  - napari=0.7
  - pyqt
  - jupyterlab
  - pip
  - pip:
    - cellpose==4.2.1.1
    - cnsplots==0.6.0
    - tttrkit @ git+https://github.com/IMCF-Biocev/tttrkit.git
